[[custom_groups]]
name = "🚀 手动选择"
type = "select"
rule = [
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "♻️ 自动选择"
type = "url-test"
rule = [".*"]
url = "https://cp.cloudflare.com/generate_204"
interval = 300
timeout = 0
tolerance = 50

[[custom_groups]]
name = "💬 即时通讯"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  "[]🎯 全球直连",
]

[[custom_groups]]
name = "🌐 社交媒体"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  "[]🎯 全球直连",
  ".*",
]

[[custom_groups]]
name = "🚀 GitHub"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  "[]🎯 全球直连",
]

[[custom_groups]]
name = "🤖 ChatGPT"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇸🇬 新加坡节点",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🤖 AI服务"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇸🇬 新加坡节点",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎶 TikTok"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "📹 YouTube"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇸🇬 新加坡节点",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎥 Netflix"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇸🇬 新加坡节点",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎥 DisneyPlus"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇸🇬 新加坡节点",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎥 HBO"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇸🇬 新加坡节点",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎥 PrimeVideo"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇸🇬 新加坡节点",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎥 AppleTV+"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇸🇬 新加坡节点",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  "[]🎯 全球直连",
  ".*",
]

[[custom_groups]]
name = "🎥 Emby"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🎯 全球直连",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎻 Spotify"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🎯 全球直连",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "📺 Bahamut"
type = "select"
rule = [
  "[]🇼🇸 台湾节点",
  "[]🚀 手动选择",
  "[]🎯 全球直连",
  ".*",
]

[[custom_groups]]
name = "🌎 国外媒体"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🛒 国外电商"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🎯 全球直连",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "📢 谷歌FCM"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
]

[[custom_groups]]
name = "🇬 谷歌服务"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🍎 苹果服务"
type = "select"
rule = [
  "[]🎯 全球直连",
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "Ⓜ️ 微软服务"
type = "select"
rule = [
  "[]🎯 全球直连",
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎮 游戏平台"
type = "select"
rule = [
  "[]🎯 全球直连",
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🎮 Steam"
type = "select"
rule = [
  "[]🎯 全球直连",
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🚀 测速工具"
type = "select"
rule = [
  "[]🎯 全球直连",
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = [
  "[]🚀 手动选择",
  "[]♻️ 自动选择",
  "[]🎯 全球直连",
  "[]🇭🇰 香港节点",
  "[]🇺🇸 美国节点",
  "[]🇯🇵 日本节点",
  "[]🇸🇬 新加坡节点",
  "[]🇼🇸 台湾节点",
  "[]🇰🇷 韩国节点",
  ".*",
]

[[custom_groups]]
name = "🔀 非标端口"
type = "select"
rule = [
  "[]🐟 漏网之鱼",
  "[]🎯 全球直连",
]

[[custom_groups]]
name = "🇭🇰 香港节点"
type = "url-test"
rule = ['(🇭🇰|港|\bHK(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|hk|Hong Kong|HongKong|hongkong|HONG KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌)']
url = "https://cp.cloudflare.com/generate_204"
interval = 300
timeout = 0
tolerance = 50

[[custom_groups]]
name = "🇺🇸 美国节点"
type = "url-test"
rule = ['(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)']
url = "https://cp.cloudflare.com/generate_204"
interval = 300
timeout = 0
tolerance = 50

[[custom_groups]]
name = "🇯🇵 日本节点"
type = "url-test"
rule = ['(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|\bJP(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)']
url = "https://cp.cloudflare.com/generate_204"
interval = 300
timeout = 0
tolerance = 50

[[custom_groups]]
name = "🇸🇬 新加坡节点"
type = "url-test"
rule = ['(🇸🇬|新加坡|坡|狮城|\bSG(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Singapore|SINGAPORE|SIN)']
url = "https://cp.cloudflare.com/generate_204"
interval = 300
timeout = 0
tolerance = 50

[[custom_groups]]
name = "🇼🇸 台湾节点"
type = "url-test"
rule = ['(🇹🇼|🇼🇸|台|新北|彰化|\bTW(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Taiwan|TAIWAN|TWN|TPE|ROC)']
url = "https://cp.cloudflare.com/generate_204"
interval = 300
timeout = 0
tolerance = 50

[[custom_groups]]
name = "🇰🇷 韩国节点"
type = "url-test"
rule = ['(🇰🇷|\bKR(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Korea|KOREA|KOR|首尔|韩|韓|春川|Chuncheon|ICN)']
url = "https://cp.cloudflare.com/generate_204"
interval = 300
timeout = 0
tolerance = 50

[[custom_groups]]
name = "🎯 全球直连"
type = "select"
rule = [
  "[]DIRECT",
  "http://wifi.vivo.com.cn/generate_204",
]
