package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"text/template"
)

type capabilityManifest struct {
	Schema        int      `json:"schema"`
	Module        string   `json:"module"`
	ModuleVersion string   `json:"module_version"`
	Schemes       []string `json:"schemes"`
}

const headerTemplate = `// Auto-generated by scripts/generate_schemes.go
// DO NOT EDIT MANUALLY
// Based on Mihomo version: {{.ModuleVersion}}

#pragma once
#include <vector>
#include <string>

namespace mihomo {
    const std::vector<std::string> SUPPORTED_SCHEMES = {
{{- range .Schemes}}
        "{{.}}",
{{- end}}
    };
}
`

func main() {
	manifestPath := flag.String("manifest", "", "path to mihomo_capabilities.json")
	outputPath := flag.String("o", "", "output path for mihomo_schemes.h")
	flag.Parse()
	if *manifestPath == "" || *outputPath == "" {
		fmt.Fprintln(os.Stderr, "usage: go run generate_schemes.go -manifest <manifest_path> -o <output_path>")
		os.Exit(1)
	}

	content, err := os.ReadFile(*manifestPath)
	if err != nil {
		fatal(err)
	}
	var manifest capabilityManifest
	if err := json.Unmarshal(content, &manifest); err != nil {
		fatal(err)
	}
	if manifest.Schema != 1 || manifest.Module != "github.com/metacubex/mihomo" ||
		manifest.ModuleVersion == "" || len(manifest.Schemes) == 0 {
		fatal(fmt.Errorf("invalid or incomplete Mihomo capability manifest"))
	}

	output, err := os.Create(*outputPath)
	if err != nil {
		fatal(err)
	}
	defer output.Close()
	if err := template.Must(template.New("header").Parse(headerTemplate)).Execute(output, manifest); err != nil {
		fatal(err)
	}
	fmt.Printf("Generated %s with %d Mihomo URI schemes\n", *outputPath, len(manifest.Schemes))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
