"""add options table and add urls.expires_at column

Revision ID: 94b0cb3b951f
Revises: 957cf6ebb2fc
Create Date: 2025-09-05 15:31:58.173181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b0cb3b951f'
down_revision: Union[str, Sequence[str], None] = '957cf6ebb2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zurl_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zurl_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zurl_options_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zurl_options_key'), ['key'], unique=True)

    with op.batch_alter_table('zurl_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.Integer(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zurl_urls', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('zurl_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zurl_options_key'))
        batch_op.drop_index(batch_op.f('ix_zurl_options_id'))

    op.drop_table('zurl_options')
    # ### end Alembic commands ###
