"""init

Revision ID: 957cf6ebb2fc
Revises: 
Create Date: 2025-08-03 22:09:33.726686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957cf6ebb2fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zurl_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('zurl_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zurl_sessions_id'), ['id'], unique=False)

    op.create_table('zurl_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(length=32), nullable=True),
    sa.Column('long_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zurl_urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zurl_urls_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zurl_urls_long_url'), ['long_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_zurl_urls_short_url'), ['short_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_zurl_urls_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zurl_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zurl_urls_title'))
        batch_op.drop_index(batch_op.f('ix_zurl_urls_short_url'))
        batch_op.drop_index(batch_op.f('ix_zurl_urls_long_url'))
        batch_op.drop_index(batch_op.f('ix_zurl_urls_id'))

    op.drop_table('zurl_urls')
    with op.batch_alter_table('zurl_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zurl_sessions_id'))

    op.drop_table('zurl_sessions')
    # ### end Alembic commands ###
