IF(NOT DEFINED INPUT_FILE OR INPUT_FILE STREQUAL "")
    MESSAGE(FATAL_ERROR "INPUT_FILE is required")
ENDIF()
IF(NOT DEFINED OUTPUT_FILE OR OUTPUT_FILE STREQUAL "")
    MESSAGE(FATAL_ERROR "OUTPUT_FILE is required")
ENDIF()
IF(NOT EXISTS "${INPUT_FILE}")
    MESSAGE(FATAL_ERROR "Dashboard source is missing: ${INPUT_FILE}")
ENDIF()

FILE(READ "${INPUT_FILE}" DASHBOARD_HEX HEX)
STRING(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1,"
    DASHBOARD_BYTE_LITERALS "${DASHBOARD_HEX}")

STRING(CONCAT DASHBOARD_GENERATED
    "// Generated from resources/dashboard/index.html. Do not edit.\n"
    "#pragma once\n\n"
    "namespace dashboard_resource {\n"
    "inline constexpr unsigned char kDashboardHtml[] = {"
    "${DASHBOARD_BYTE_LITERALS}"
    "};\n"
    "} // namespace dashboard_resource\n")

GET_FILENAME_COMPONENT(OUTPUT_DIRECTORY "${OUTPUT_FILE}" DIRECTORY)
FILE(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
FILE(LOCK "${OUTPUT_FILE}.lock"
    GUARD PROCESS
    TIMEOUT 30
    RESULT_VARIABLE DASHBOARD_LOCK_RESULT)
IF(NOT DASHBOARD_LOCK_RESULT STREQUAL "0")
    MESSAGE(FATAL_ERROR
        "Unable to lock Dashboard output: ${DASHBOARD_LOCK_RESULT}")
ENDIF()

STRING(RANDOM LENGTH 16 ALPHABET 0123456789abcdef TEMPORARY_SUFFIX)
SET(TEMPORARY_OUTPUT "${OUTPUT_FILE}.${TEMPORARY_SUFFIX}.tmp")
FILE(WRITE "${TEMPORARY_OUTPUT}" "${DASHBOARD_GENERATED}")

IF(EXISTS "${OUTPUT_FILE}")
    EXECUTE_PROCESS(
        COMMAND "${CMAKE_COMMAND}" -E compare_files
                "${TEMPORARY_OUTPUT}" "${OUTPUT_FILE}"
        RESULT_VARIABLE DASHBOARD_COMPARE_RESULT)
    IF(DASHBOARD_COMPARE_RESULT EQUAL 0)
        FILE(REMOVE "${TEMPORARY_OUTPUT}")
        RETURN()
    ENDIF()
ENDIF()

IF(DASHBOARD_EMBED_TEST_FAIL_BEFORE_RENAME)
    FILE(REMOVE "${TEMPORARY_OUTPUT}")
    MESSAGE(FATAL_ERROR
        "Injected Dashboard failure before atomic output replacement")
ENDIF()
FILE(RENAME "${TEMPORARY_OUTPUT}" "${OUTPUT_FILE}")
