#!/usr/bin/env bash
set -euo pipefail

: "${THREADS:?THREADS is required}"
: "${SHA:?SHA is required}"
: "${VERSION:?VERSION is required}"
: "${BUILD_DATE:?BUILD_DATE is required}"
: "${DEPENDENCY_SNAPSHOT_SHA:?DEPENDENCY_SNAPSHOT_SHA is required}"
: "${MIHOMO_REF:?MIHOMO_REF is required}"
: "${QUICKJSPP_REF:?QUICKJSPP_REF is required}"
: "${LIBCRON_REF:?LIBCRON_REF is required}"
: "${TOML11_REF:?TOML11_REF is required}"
: "${CPP_HTTPLIB_REF:?CPP_HTTPLIB_REF is required}"
: "${NLOHMANN_JSON_REF:?NLOHMANN_JSON_REF is required}"
: "${INJA_REF:?INJA_REF is required}"
: "${JPCRE2_REF:?JPCRE2_REF is required}"
: "${GO_IMAGE:?GO_IMAGE is required}"
: "${DEBIAN_IMAGE:?DEBIAN_IMAGE is required}"
: "${ALPINE_IMAGE:?ALPINE_IMAGE is required}"
: "${DEBIAN_TRIXIE_IMAGE:?DEBIAN_TRIXIE_IMAGE is required}"
: "${DEBIAN_TRIXIE_SLIM_IMAGE:?DEBIAN_TRIXIE_SLIM_IMAGE is required}"

MIHOMO_CACHE_BUST="${MIHOMO_CACHE_BUST:-${DEPENDENCY_SNAPSHOT_SHA}}"
SOURCE_DEPS_CACHE_BUST="${SOURCE_DEPS_CACHE_BUST:-${DEPENDENCY_SNAPSHOT_SHA}}"
REFRESH_GO_DEPS="${REFRESH_GO_DEPS:-false}"
REFRESH_HEADERS="${REFRESH_HEADERS:-false}"
BUILD_TESTS="${BUILD_TESTS:-true}"

cat <<EOF
THREADS=${THREADS}
SHA=${SHA}
VERSION=${VERSION}
BUILD_DATE=${BUILD_DATE}
DEPENDENCY_SNAPSHOT_SHA=${DEPENDENCY_SNAPSHOT_SHA}
MIHOMO_REF=${MIHOMO_REF}
MIHOMO_CACHE_BUST=${MIHOMO_CACHE_BUST}
SOURCE_DEPS_CACHE_BUST=${SOURCE_DEPS_CACHE_BUST}
QUICKJSPP_REF=${QUICKJSPP_REF}
LIBCRON_REF=${LIBCRON_REF}
TOML11_REF=${TOML11_REF}
CPP_HTTPLIB_REF=${CPP_HTTPLIB_REF}
NLOHMANN_JSON_REF=${NLOHMANN_JSON_REF}
INJA_REF=${INJA_REF}
JPCRE2_REF=${JPCRE2_REF}
GO_IMAGE=${GO_IMAGE}
DEBIAN_IMAGE=${DEBIAN_IMAGE}
ALPINE_IMAGE=${ALPINE_IMAGE}
DEBIAN_TRIXIE_IMAGE=${DEBIAN_TRIXIE_IMAGE}
DEBIAN_TRIXIE_SLIM_IMAGE=${DEBIAN_TRIXIE_SLIM_IMAGE}
REFRESH_GO_DEPS=${REFRESH_GO_DEPS}
REFRESH_HEADERS=${REFRESH_HEADERS}
BUILD_TESTS=${BUILD_TESTS}
EOF
